services:
  chat:
    container_name: chat_container
    build:
      context: .
      target: development
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_URL: "file:/app/server/database/database.db" # or the regular file?
    ports:
      - "8004:3000"
    volumes:
      - ./src:/app/src  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
    tty: true

